version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_SWAPI_URL=https://swapi.dev/api
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped